remote_theme: pmarsceill/just-the-docs
title: "My Project Documentation"
description: "Comprehensive guides and documentation"
logo: "/assets/images/logo.png"

just_the_docs:
  color_scheme: light
  search:
    enabled: true
  nav:
    - title: "Getting Started"
      items:
        - name: "Introduction"
          link: /getting-started/introduction
        - name: "Installation"
          link: /getting-started/installation
    - title: "Features"
      items:
        - name: "Feature 1"
          link: /features/feature1
        - name: "Feature 2"
          link: /features/feature2
