remote_theme: pmarsceill/just-the-docs
title: "My Documentation Site"
description: "A documentation site similar to GitHub Docs."

just_the_docs:
  logo: "/assets/images/logo.png"  # Optional: specify path to logo
  color_scheme: light  # Choose light or dark color scheme
  search:
    enabled: true  # Enable search functionality
  nav:
    - title: "Quickstart"
      url: /quickstart/
    - title: "About GitHub Copilot"
      children:
        - title: "Setup"
          children:
            - title: "Setup Instructions"
              url: /setup/setup-instructions/
        - title: "Use GitHub Copilot"
          children:
            - title: "Best Practices"
              url: /use-github-copilot/best-practices/
            - title: "Get Code Suggestions"
              url: /use-github-copilot/get-code-suggestions/
            - title: "Chat in IDE"
              url: /use-github-copilot/chat-in-ide/
  additional_css:
    - assets/css/custom.css
