name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: '0.134.2'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Hugo CLI
        run: |
          wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb \
          && sudo dpkg -i hugo.deb

      - name: Build with Hugo
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: ./public
